export default {
  'usage-meter': 'UsageMeter',
  'resource-name-cell': 'ResourceNameCell',
  'property-list': 'PropertyList',
  card: 'Card',
  table: 'Table',
  tabs: 'Tabs',
  tooltip: 'Tooltip',
  'empty-state': 'Empty',
  progress: 'Progress',
  'data-table': 'DataTable',
  'chart': 'Chart',
  'kpi-card': 'KPICard',
  'progress-ring': 'ProgressRing',
  'resource-chart': 'ResourceChart',
  'status-indicator': 'StatusIndicator',
}
