export default {
  input: 'Input',
  textarea: 'Textarea',
  select: 'Select',
  checkbox: 'Checkbox',
  'radio-group': 'Radio',
  switch: 'Switch',
  toggle: 'Toggle / ToggleGroup',
  form: 'Form',
  'number-field': 'NumberField',
  'date-range-picker': 'DateRangePicker',
  'searchable-select': 'SearchableSelect',
  'toggle-group': 'ToggleGroup',
  'label-editor': 'LabelEditor',
}
